# Change this to set a different Project file name
project.name = "CppUniverse"

# Replace this with your class prefix for Objective-C files.
project.class_prefix = "PCU"

# By default Xcake defaults to creating the standard Debug and Release
# configurations, uncomment these lines to add your own.
#
#debug_configuration :Staging
#debug_configuration :Debug
#release_configuration :Release

# Change these to the platform you wish to support (ios, osx) and the
# version of that platform (8.0, 9.0, 10.10, 10.11)
#
application_for :ios, 11.1 do |target|

    #Update these with the details of your app
    target.name = project.name
    target.all_configurations.each { |c| c.product_bundle_identifier = "com.github.piasy.CppUniverse"}

    # Uncomment to target iPhone devices only
    #
    # File patterns can be seen here https://guides.cocoapods.org/syntax/podspec.html#group_file_patterns
    #
    #target.all_configurations.each { |c| c.supported_devices = :iphone_only}

    # Uncomment this to include additional files

    target.include_files << "../djinni/support-lib/objc/**.*"
    target.include_files << "../src/cpp/**.*"
    target.include_files << "../generated_src/cpp/**.*"
    target.include_files << "../generated_src/objc/**.*"
    target.include_files << "../libs/ios/arm64/*.a"
    target.include_files << "../libs/ios/arm64/boost.framework"

    # Uncomment this to exclude additional files
    #
    # File patterns can be seen here https://guides.cocoapods.org/syntax/podspec.html#group_file_patterns
    #
    #target.exclude_files << "ExcludeToInclude/*.*"

    target.all_configurations.each do |c|
      c.settings["INFOPLIST_FILE"] = "Info.plist"
      c.settings["OTHER_LDFLAGS"] = "$(inherited) -lz"
      c.settings["FRAMEWORK_SEARCH_PATHS"] = "$(inherited) $(PROJECT_DIR)/../libs/ios/arm64"
      c.settings["LIBRARY_SEARCH_PATHS"] = "$(inherited) $(PROJECT_DIR)/../libs/ios/arm64"
      c.settings["HEADER_SEARCH_PATHS"] = "$(inherited) /Users/piasy/tools/vagrant/ubuntu_xenial64/cpprestsdk/Release/include/ /Users/piasy/tools/vagrant/ubuntu_xenial64/cpprestsdk/Build_iOS/openssl/include/ $(PROJECT_DIR)/../libs/ios/arm64/boost.framework/Headers/"

      c.settings["ENABLE_BITCODE"] = "NO"
    end

    # Uncomment to set your own build settings
    #
    #target.all_configurations.each { |c| c.settings["ENABLE_BITCODE"] = "NO"}
    #target.all_configurations.each { |c| c.settings["GCC_PREFIX_HEADER"] = "APP-Prefix-Header.pch"}
    #target.all_configurations.each { |c| c.settings["SWIFT_OBJC_BRIDGING_HEADER"] = "APP-Bridging-Header.h"}

    # Uncomment to define your own preprocessor macros
    #
    #target.all_configurations.each { |c| c.preprocessor_definitions["API_ENDPOINT"] = "https://example.org".to_obj_c}

    # Comment to remove Unit Tests for your app
    #
    # unit_tests_for target

    # Uncomment to create a Watch App for your application.
    #
    #watch_app_for target, 2.0
end
